# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eb48f353d818ac66040f374b6d0f65acd2fc45af7f28bac9a5a29e2d1fa1db57aeb3638e045364c8549239f001201dbde03b1e0976b8a1cc3d278d790f06c4b

test:
  secret_key_base: e2ddbdd62c2d1013b871a9fd270551a9157f36ff422f6e45a9d6310316e969206b1968b1ee9285aca84911ccfafef74f71cb0ebecffd6e2fb87a4c324e14ed71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
